name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test -v -count 1 -coverprofile=coverage.out